from __future__ import annotations

from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from src.api.deps import get_current_admin
from src.db.models import Admin, Resident
from src.db.session import get_db
from src.schemas.resident import ResidentCreate, ResidentOut, ResidentUpdate

router = APIRouter(prefix="/residents", tags=["residents"])


def _apply_search(stmt, q: Optional[str]):
    """
    Apply case-insensitive search across resident fields.

    We use ILIKE which is supported by PostgreSQL.
    """
    if not q:
        return stmt

    query = q.strip()
    if not query:
        return stmt

    pattern = f"%{query}%"
    return stmt.where(
        or_(
            Resident.name.ilike(pattern),
            Resident.address.ilike(pattern),
            Resident.phone.ilike(pattern),
            Resident.email.ilike(pattern),
        )
    )


@router.get(
    "",
    response_model=List[ResidentOut],
    summary="List residents (with optional search)",
    description=(
        "Return a paginated list of residents. Requires admin authentication.\n\n"
        "Optional search:\n"
        "- `q`: Searches case-insensitively across name, address, phone, and email.\n"
        "Pagination:\n"
        "- `page` is 1-based\n"
        "- `page_size` capped to 100"
    ),
    operation_id="residents_list",
)
def list_residents(
    q: Optional[str] = Query(
        default=None,
        description="Optional search query applied to name/address/phone/email (case-insensitive).",
        max_length=200,
    ),
    page: int = Query(1, ge=1, description="1-based page index."),
    page_size: int = Query(20, ge=1, le=100, description="Number of items per page (max 100)."),
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin),
) -> List[ResidentOut]:
    """
    List residents with optional search and pagination.

    Args:
        q: Optional search term, matched against name/address/phone/email.
        page: 1-based page index.
        page_size: Items per page (max 100).
        db: Database session dependency.
        current_admin: Authenticated admin (JWT bearer).

    Returns:
        A list of residents for the requested page.
    """
    _ = current_admin  # Explicitly mark dependency usage for auth guard.

    stmt = select(Resident).order_by(Resident.id.asc())
    stmt = _apply_search(stmt, q)

    offset = (page - 1) * page_size
    stmt = stmt.offset(offset).limit(page_size)

    residents = db.scalars(stmt).all()
    return residents


@router.get(
    "/{resident_id}",
    response_model=ResidentOut,
    summary="Get a resident by ID",
    description="Fetch a single resident record by ID. Requires admin authentication.",
    operation_id="residents_get",
)
def get_resident(
    resident_id: int,
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin),
) -> ResidentOut:
    """
    Get a resident by ID.

    Args:
        resident_id: Resident ID.
        db: Database session dependency.
        current_admin: Authenticated admin (JWT bearer).

    Returns:
        The resident record.

    Raises:
        HTTPException(404): If resident does not exist.
    """
    _ = current_admin

    resident = db.get(Resident, resident_id)
    if resident is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Resident not found")
    return resident


@router.post(
    "",
    response_model=ResidentOut,
    status_code=status.HTTP_201_CREATED,
    summary="Create a resident",
    description="Create a new resident record. Requires admin authentication.",
    operation_id="residents_create",
)
def create_resident(
    payload: ResidentCreate,
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin),
) -> ResidentOut:
    """
    Create a resident.

    Args:
        payload: ResidentCreate payload.
        db: Database session dependency.
        current_admin: Authenticated admin (JWT bearer).

    Returns:
        The created resident.

    Notes:
        Uses commit + refresh to populate autogenerated fields (id, timestamps).
    """
    _ = current_admin

    resident = Resident(
        name=payload.name,
        address=payload.address,
        phone=payload.phone,
        email=str(payload.email),
        photo_url=payload.photo_url,
    )
    db.add(resident)
    db.commit()
    db.refresh(resident)
    return resident


@router.put(
    "/{resident_id}",
    response_model=ResidentOut,
    summary="Update a resident",
    description=(
        "Update an existing resident record by ID. Requires admin authentication.\n\n"
        "This is a partial update: only provided fields are modified."
    ),
    operation_id="residents_update",
)
def update_resident(
    resident_id: int,
    payload: ResidentUpdate,
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin),
) -> ResidentOut:
    """
    Update a resident.

    Args:
        resident_id: Resident ID.
        payload: ResidentUpdate payload (partial fields).
        db: Database session dependency.
        current_admin: Authenticated admin (JWT bearer).

    Returns:
        The updated resident.

    Raises:
        HTTPException(404): If resident does not exist.
    """
    _ = current_admin

    resident = db.get(Resident, resident_id)
    if resident is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Resident not found")

    update_data = payload.model_dump(exclude_unset=True)

    # Apply updates safely.
    for field, value in update_data.items():
        if field == "email" and value is not None:
            value = str(value)
        setattr(resident, field, value)

    db.add(resident)
    db.commit()
    db.refresh(resident)
    return resident


@router.delete(
    "/{resident_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a resident",
    description="Delete a resident record by ID. Requires admin authentication.",
    operation_id="residents_delete",
)
def delete_resident(
    resident_id: int,
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin),
) -> Response:
    """
    Delete a resident by ID.

    Args:
        resident_id: Resident ID.
        db: Database session dependency.
        current_admin: Authenticated admin (JWT bearer).

    Returns:
        Empty response with HTTP 204.

    Raises:
        HTTPException(404): If resident does not exist.
    """
    _ = current_admin

    resident = db.get(Resident, resident_id)
    if resident is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Resident not found")

    db.delete(resident)
    db.commit()
    return Response(status_code=status.HTTP_204_NO_CONTENT)
